### ISSUE TITLE
为什么不能使用OSS定义的主题

### ISSUE THREAD

**Issue by leadroy** [xiaomac/oss-upload#1]
很好的插件，可是我定义了使用：使用样式图片服务，并在阿里上设置了样式，但是写的文章里的所有图片链接还是全部调用-full这个样式。
包括文章列表中的略缩图也是调用-FULL这个样式。

这样就失去了加速的意义了。我不知道是我设置问题还是插件本身的问题。
原来以为是主题问题，更换了很多主题都是这种情况。

@xiaomac

**Comment by leadroy** [comment]
可以通过这个地址看问题点：
https://www.ams365.cn/news

**Comment by xiaomac** [comment]
你这个情况应该是服务器没装PHP图片处理的扩展，导致无法自动生成缩略图的META信息。
——可以试试禁用插件看看默认上传是否有缩略图。

**Comment by leadroy** [comment]
应该不是这个问题，我用WORDPRESS的站点健康工具，所有需要安装的工具都已完成，包括了PHP的相关插件。是否可以使用什么工具测试原由的？应该不是我一个人遇到这种问题。

**Comment by xiaomac** [comment]
你这个情况我没办法重现，也没有其他人反馈同样问题。最好还是要进后台看看。
