### ISSUE TITLE
使用webp格式的时候遇到的一点问题

### ISSUE THREAD

**Issue by xgblack** [xiaomac/oss-upload#10]
直接在浏览器访问网站链接（https://blog.xgblack.cn/ ）图片是可以转换为webp的（见图一），但是如果是通过点击页面上的“首页”选项，或者网站logo什么的（以跳转的方式返回网站首页）时，图片不会转为webp（见图二）。插件设置见图三
![image](https://user-images.githubusercontent.com/30540766/79124461-ec55c380-7dce-11ea-9002-aacee28c46a0.png)
![image](https://user-images.githubusercontent.com/30540766/79124616-48b8e300-7dcf-11ea-8333-695e3dd73825.png)
![image](https://user-images.githubusercontent.com/30540766/79124697-77cf5480-7dcf-11ea-8728-2a0037b9adfb.png)

**Comment by xiaomac** [comment]
确认了，这是你主题的不刷新效果（/wp-json/pandastudio/nirvana/restapi/）导致丢失了 accept 头，所以代码认为浏览器不支持 webp，就没做处理。

这个情况问题不大，你暂时忽略即可。新版我会更换为 html5 的 picture 标签来支持 webp。
