### ISSUE TITLE
启用插件后, 以前的资源文件全部404

### ISSUE THREAD

**Issue by HarrisonQi** [xiaomac/oss-upload#11]
非常感谢作者的插件. 
我的网站启用插件前已经有了很多图片等资源文件. 启用插件后, 之前的资源文件host被强制替换成了插件中配置的OSS的访问域名. 

请问插件是不兼容旧的资源文件吗? 是否提供了将原先的资源文件host转为OSS的host的功能?

**Comment by xiaomac** [comment]
是的。

代码上是可以做一些额外的判断来兼容本地的媒体资源，但这个做法我理解违反了使用OSS的初衷。

所以我的建议是：将本地资源都上传到OSS；或者不用OSS。

**Comment by HarrisonQi** [comment]
网站的资源文件已经达到一定规模, 无法转移.

所以这个插件以后也不会兼容旧文件的存储吗? 

恐怕大多数的新站长都不会立刻去安装OSS插件, 而是用了一段时间后才会发现三方文件存储的重要性. 若不能兼容旧资源文件, 这个插件恐怕只是提供给有经验的老站长吧... 相信加入了兼容旧文件的功能后, 你的插件将比现在更受欢迎.

**Comment by xiaomac** [comment]
一开始的版本是有兼容的逻辑的，但接着就会人有“开然后关然后再开然后再关”之类的各种情况出来。

超出了我的理解范畴，所以直接去掉了。要不你用OSS，要么你不用OSS。这种只用一半的，其实并不多见。

定义下你的这个“一定规模”？

**Comment by HarrisonQi** [comment]
"一定规模"指的是资源文件数量成千上万. 迁移时间成本过高. 不可能为了某个开源插件而整体迁移, 风险太大.

本ISSUE只是提一条建议, 若能力或时间有限忽略即可😓. 

目前已使用CDN加速, 效果很好.
