### ISSUE TITLE
文件自动重命名使用了MD5,这样不是安全的

### ISSUE THREAD

**Issue by lei-mu** [xiaomac/oss-upload#12]
我看了你的文件重命名方法使用了md5,这样无法保证文件名唯一，可能会造成文件替换。希望换成uuid

**Comment by Stark-X** [comment]
> 我看了你的文件重命名方法使用了md5,这样无法保证文件名唯一，可能会造成文件替换。希望换成uuid

什么样的情况会造成文件替代？”希望“ 换成 ”建议“ 比较好

**Comment by lei-mu** [comment]
> > 我看了你的文件重命名方法使用了md5,这样无法保证文件名唯一，可能会造成文件替换。希望换成uuid
> 
> 什么样的情况会造成文件替代？”希望“ 换成 ”建议“ 比较好

a用户上传一个文件名为a.png的图片后。b用户也上传了一个名为a.png的图片。因为md5后文件名相同，b的图片会替换a的那个图片。我认为这是个你的bug,所以我不‘建议’而是‘希望’尽快修复

**Comment by xiaomac** [comment]
关于重命名，按照惯例一般是采用毫秒时间戳。我采用md5，其实想偷懒，代码可以最短。

关于md5无法保持唯一这个真心不是插件考虑的范畴，重命名本身就是不推荐的。要用也行，但不会耗费什么逻辑在上面。

真相是：wp_handle_upload_prefilter 钩子中，重命名之后，会再次用 wp_unique_filename 验证本地和OSS的双重唯一性，如果发现文件已存在，会自动加后缀的。

**Comment by lei-mu** [comment]
> 关于重命名，按照惯例一般是采用毫秒时间戳。我采用md5，其实想偷懒，代码可以最短。
> 
> 关于md5无法保持唯一这个真心不是插件考虑的范畴，重命名本身就是不推荐的。要用也行，但不会耗费什么逻辑在上面。
> 
> 真相是：wp_handle_upload_prefilter 钩子中，重命名之后，会再次用 wp_unique_filename 验证本地和OSS的双重唯一性，如果发现文件已存在，会自动加后缀的。

我发现这个判断重复自动加序号的设计了。所以我把评论删了。
毫秒时间戳也不能保证唯一

**Comment by lei-mu** [comment]
如果多个wordpress 都用了同一个储存桶，并且都用了你的oss 插件，key就有可能重复。

**Comment by xiaomac** [comment]
故意的，无解。你可以有一万种方式重复。
你有两个小孩，起了一样的名字，然后还说老是喊错。
