### ISSUE TITLE
报错“图像后期处理失败，可能是服务器忙或没有足够的资源。请尝试上传较小的文件。推荐的最大尺寸为2500像素”

### ISSUE THREAD

**Issue by lei-mu** [xiaomac/oss-upload#18]
图片上传报错
`图像后期处理失败，可能是服务器忙或没有足够的资源。请尝试上传较小的文件。推荐的最大尺寸为2500像素`

上传很小的图片 依旧报错。

在评论里面看到几个提出相同问题的

![2CBCB06A-6D60-4275-A936-20C948677049](https://user-images.githubusercontent.com/29419129/122010839-139e8b00-cdee-11eb-8e55-7e77f7372e43.png)

下面是我的报错截图

![13262ABD-3251-41fd-B199-FF119D52858F](https://user-images.githubusercontent.com/29419129/122011764-09c95780-cdef-11eb-91d3-7b44f84159b6.png)

这个问题 什么时候能修复

**Comment by yimo0871** [comment]
伸手党要有爱
