### ISSUE TITLE
oss插件和the7主题不兼容

### ISSUE THREAD

**Issue by luyu99998888** [xiaomac/oss-upload#2]
the7主题会在wp-content/uploads目录下创建各种文件，开启oss插件后会导致the7主题样式丢失

the7在wp-content/uploads下创建这两个目录smile_fonts、the7-css，有没有办法排除上传这两个目录到oss

开启oss插件，the7主题会报错：“无法创建自定义.CSS文件。 为了提高您的网站性能，请检查是否创建了“.../wp-content/uploads/”文件夹，其CHMOD设置为755。”

**Comment by xiaomac** [comment]
这个主题我确认做过兼容的，得具体看看代码了。另外目前也没有打算做目录排除的逻辑，会很混乱。

**Comment by xiaomac** [comment]
先试试最新版本，有什么问题再反馈吧。
