### ISSUE TITLE
望添加传输加速节点支持

### ISSUE THREAD

**Issue by sarkrui** [xiaomac/oss-upload#3]
目前仅支持
```
oss-cn-hangzhou.aliyuncs.com
oss-cn-shenzhen.aliyuncs.com
oss-cn-shanghai.aliyuncs.com
[...]
oss-cn-hangzhou-internal.aliyuncs.com
```
[BUCKET].oss-accelerate.aliyuncs.com 的 endpoint 目前还是暂不支持的，海外 VPS 上传到杭州 oss 会非常慢，经常出现上传失败情况。

**Comment by xiaomac** [comment]
本来就是支持的。填 oss-accelerate.aliyuncs.com 即可。不要带 BUCKET。

**Comment by sarkrui** [comment]
那可能是 Aliyun OSS 的问题 `ping oss-accelerate.aliyuncs.com` 是不通的，需要加 [bucket] 前缀才通

**Comment by xiaomac** [comment]
没毛病。lib中会从 oss://BUCKET 值中获取 bucket，再拼成为最终的域名。

**Comment by sarkrui** [comment]
> 没毛病。lib 中会从 oss://BUCKET 值中获取 bucket，再拼成为最终的域名。

亲测有效👍
