### ISSUE TITLE
[bug] 访问 OSS Upload 图片 URL 是以附件形式下载而非图片预览

### ISSUE THREAD

**Issue by sarkrui** [xiaomac/oss-upload#4]
问题如题。
`Content-type` 确实是 `image/jpg` 了，但 `content-disposition` 属性为: `attachment` (需要为`inline`?) 可能这样导致图片不是预览形式展现吧？
```
https://pxing-cn-hz.oss-cn-hangzhou.aliyuncs.com/2019/11/Image_16-1-scaled.jpg?x-oss-process=style%2Fportfolio-single-img-4
```
<img width="320" alt="Screenshot 2020-03-05 18 28 15" src="https://user-images.githubusercontent.com/14228455/76008400-e2a78900-5f0f-11ea-847e-a5a28ac55ae1.png">

**Comment by xiaomac** [comment]
问题已经修正，下个版本更新。

原因：OSS本身有些傻，image/jpeg，image/png 等格式都无法打开，需要设置为 image/jpg。

**Comment by xiaomac** [comment]
追加：如果涉及样式、原图保护、格式转化等，的话。
