### ISSUE TITLE
缩略图质量设置只在参数样式的图片服务下有效

### ISSUE THREAD

**Issue by sarkrui** [xiaomac/oss-upload#6]
应该不算是 bug，用 OSS 样式的图片服务，OSS Upload 的`缩略图质量`是无效的，需要自行在 OSS 图片样式添加 `/quality,q_80` 或 `/quality,Q_80`，或许在设置项添加说明：`仅在参数样式的图片服务下有效会比较清楚`（我是从 Aliyun OSS 插件转过来的，所以默认使用 OSS 的 sytle service，但这个图片质量功能无效稍微困扰了我一下），顺便附上我在 Aliyun OSS 插件自动生成的 OSS 样式模板，在OSS `数据处理` - `图片处理` - `导入样式`即可。
[OSS 图片样式设置模板.txt](https://github.com/xiaomac/oss-upload/files/4303097/OSS.txt)

**Comment by xiaomac** [comment]
是的。样式本身也包含参数的功能，是高级功能。不矛盾。

设置界面是比较凌乱，以后有大的功能改进再优化了。
