### ISSUE TITLE
“图片样式”在B2主题的后台编辑器，full样式不会自动添加到末尾，webp格式图像不生效

### ISSUE THREAD

**Issue by liluo-publish** [xiaomac/oss-upload#8]
不好意思，冒昧的问一下2个问题。

-  测试了默认主题，图片链接样式末尾是正常添加的。但是B2主题medium/large都正常，就是full样式有问题
- 后台开启webp，前台图片链接不会替换成webp格式

如果不方便的话，帮忙指出可能导致的原因也可

**Comment by xiaomac** [comment]
1、这个“有问题”不太明白。是没添加，还是添加错，可有出错链接？

2、会判断浏览器是否支持，不是一定会替换。同样最好有链接。
