### ISSUE TITLE
建议支持使用 HTTPS 访问阿里云

### ISSUE THREAD

**Issue by qin-nz** [xiaomac/oss-upload#9]
在阿里云控制台中，如果给 Assess Token 用户的授权条件中增加仅允许 HTTPS 访问时，这个插件的 `测试一下` 按钮会提示错误，去掉这个限制后正常。
因此判断你在访问阿里云时使用了 http 而非 https，建议使用 https 访问。

**Comment by xiaomac** [comment]
不太清楚”给 Assess Token 用户的授权条件中增加仅允许 HTTPS 访问时“是什么操作，也找不到相关的功能。

测试时是走OSS文件协议，跟https啥的无关。

提示错误又是啥错误，应该是你设置问题。

**Comment by qin-nz** [comment]
相关功能：
![image](https://user-images.githubusercontent.com/6998071/79415006-c0a92800-7fde-11ea-8403-eb920778beb4.png)


![image](https://user-images.githubusercontent.com/6998071/79414965-a1aa9600-7fde-11ea-934e-e87be47e8525.png)

修复办法：把这里改成 true

https://github.com/xiaomac/oss-upload/blob/5382454b0e28aac33c340555b240d2ac0808746f/lib/OSS.php#L2081

**Comment by xiaomac** [comment]
666，还真是。从来没用过这个设置。新版这里会默认改为 ture，现在很少用http了。
